theme: jekyll-theme-cayman
defaultLang: es
relative_links:
  enabled: true
  collections: true
title: [TFG(Re)Search]
description: [Líneas de Investigación]
logo: /assets/img/logo-tri.png
markdown: kramdown
include:
  - README.md
  - mapli/numerico.md
  - mapli/polinomios-ort.md
  - mapli/convexo.md
  - algebra/resumenes/semigrupos-numericos.md
